### ISSUE TITLE
How up to date is the pact_broker gem?

### ISSUE THREAD

**Issue by bethesque** [nadnerb/terraform-pact-broker#1]
Does it automatically pull in the latest version, or is it fixed to a particular one?

**Comment by corroded** [comment]
@bethesque did you end up using this? Looks like from the code, it just pulls the latest code in the master branch in github

**Comment by bethesque** [comment]
I think I was trying to work out if there was an image (like Docker) somewhere that needed to be updated, and I can't remember what the answer was. I think we can close this though.
